= Vertx-stock-broker

image:https://img.shields.io/badge/vert.x-4.5.7-purple.svg[link="https://vertx.io"]

This application was generated using http://start.vertx.io

== Building

To launch your tests:
```
./mvnw clean test
```

To package your application:
```
./mvnw clean package
```

To run your application:
```
./mvnw clean compile exec:java
```

== VERT.X Config

* We can use Vert.X config to configure our application.
* It supports the below formats. JSON, Properties, YAML (using extensions), Hocon (using extensions)
* It supports multiple stores
  - System Properties
  - Environment properties
  - files
  - Event Bus
  - Kubernetes Config Map (using extensions)
  - & more
* We can use multiple stores in VertX configuration. It means we can use the same property in multiple stores and can define overriding rules to prioritize a particular store. Environment variables have the highest priority and we can change the priority by modifying the order we add the stores in ConfigRetrieverOptions.
* To use Vert.X config, use the below dependency in pom.xml
```
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-config</artifactId>
</dependency>
```

== TODO
* Learn about Objects.isNull

== Help

* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://discord.gg/6ry7aqPWXy[Vert.x Discord]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]


